version: '3.7'

services:

  onboarding-app:
    container_name: onboarding-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4001:80'